name: "NUtils"
version: '${version}'
main: me.nhall.nutil.NUtil
api-version: 1.17
description: Discord Bot Link to Whitelist People from the GO's Discord
commands:
  nreload:
    description: Reload Config
    usage: /<command>
    permission: n.reload